
version: '3.8'
services:
  db:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - /f/Postgres/data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
  pg4:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PYTHONPATH=/pgadmin4
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - '5050:80'
    volumes: 
      - /f/Postgres/pgadmin:/var/lib/pgadmin
    networks:
      - postgres
networks:
  postgres:
    driver: bridge